services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  django_app:
    build: ./server
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    environment:
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: my_database
      DB_USER: my_username
      DB_PASSWORD: my_password
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_CHARSET: utf8mb4
    depends_on:
      - mysql_db
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: